### ISSUE TITLE
Cars dataset: provide cleaned up data and sample data?

### ISSUE THREAD

**Issue by krasch** [wimlds/berlin-ds-lab#1]
The original dataset is roughly 2GB, scattered over ~15 files. I previously always put a merged and cleaned version on a USB drive and gave it to the students. But maybe that is not necessary? All code to create the cleaned data is in the notebook.

**Comment by noatamir** [comment]
I agree. Notebook looks clear and if a learner has issues there it's good to work them out with their peers.
Closing issue.
