### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by krasch** [wimlds/berlin-ds-lab#2]
Should we have them use some agile process and some tools like trello or so? I had that in the HTW lab, but then that was a project management master programm...

**Comment by noatamir** [comment]
I think it'll be valuable experience to practice that style of team communication before joining an agile team. I like trello and asana, we can ask them for preferences in the kick-off meeting.
@krasch let me know if you think otherwise.

**Comment by krasch** [comment]
Agreed
