### ISSUE TITLE
Technical handover

### ISSUE THREAD

**Issue by krasch** [wimlds/berlin-ds-lab#3]
What are we thinking there? Nice clean code repository they can share in their CV?

**Comment by noatamir** [comment]
Yes. Very valuable to practice code communication and looks great in their personal github. 

Should we ask them to collab on one team repository or each have their own?

**Comment by krasch** [comment]
Better to learn to work on the same repository, but then one of them will be the "host". Let's bring that up at the kick-off and let them decide.
